rel_project/rel_app/urls.py
from django.urls import path
from . import views

app_name = 'rel_app'

urlpatterns=[
    path('relative/',views.relative,name='relative'),
    path('another/',views.another,name = 'another'),
]

rel_project/rel_project/urls.py
from django.contrib import admin
from django.urls import path,include
from rel_app import views

app_name = 'rel_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('rel_app/',include('rel_app.urls'),name=app_name),
    path('admin/', admin.site.urls),
]

rel_project/rel_app/models.py
from django.db import models

# Create your models here.

rel_project/rel_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    index_dict = {'text':'hello world','number':100}
    return render(request,'rel_app/index.html',index_dict)

def relative(request):
    return render(request,'rel_app/relative.html')


def another(request):
    return render(request,'rel_app/another.html')

rel_project/templates/rel_app/another.html
<!DOCTYPE html>
{% extends "rel_app/base.html" %}
  {% block body_block %}
    <h1>Another page</h1>
  {% endblock %}

rel_project/templates/rel_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Template Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rel_app:relative' %}">Relative</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'rel_app:another' %}">Other</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}

      {% endblock %}


    </div>

  </body>
</html>

rel_project/templates/rel_app/index.html
<!DOCTYPE html>
{% extends "rel_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to tutorial</h1>

    <h1>{{ text|cut:'world' }}</h1>
    <h3>{{ number|add:"99" }}</h3>

  {% endblock %}

rel_project/templates/rel_app/relative.html
<!DOCTYPE html>
{% extends "rel_app/base.html" %}
  {% block body_block %}

    <h1>This is relative page page</h1>

  {% endblock %}